Initial Commit
SRJC-Computer-Science-Club/line-follower pull request #8
Opened 2016-12-27 01:12 UTC by fuzzybear3

Sensor Class incuding .h and .cpp file. Created LFRobot namespace.

2016-12-27 05:48 UTC, blhough requested changes

2016-12-27 05:48 UTC, blhough commented on Sensor.cpp
> +		}
if pin is HIGH then no value is returned

2016-12-27 05:48 UTC, blhough commented on Sensor.cpp
> +		}
`return digitalRead(pin) == low;`
handles both cases in one line

2016-12-27 05:48 UTC, blhough commented on Sensor.cpp
> +		pinMode(pin, INPUT);
careful, you use `pin` before you initialize it.
It's best to use an initializer list to guarantee the variable is initialized before you use it

2016-12-28 02:24 UTC, fuzzybear3 commented on Sensor.cpp
> +		pinMode(pin, INPUT);
what is an initializer list?

2016-12-28 02:25 UTC, fuzzybear3 commented on Sensor.cpp
> +		}
clever...

2016-12-28 04:24 UTC, blhough commented on Sensor.cpp
> +		pinMode(pin, INPUT);
member initializer list:
http://www.learncpp.com/cpp-tutorial/8-5a-constructor-member-initializer-lists/

2016-12-31 15:42 UTC, blhough approved these changes

2016-12-31 15:44 UTC, blhough commented
Lets keep this PR to just the sensor class and leave the sensor array for another one

2016-12-31 15:47 UTC, blhough submitted a review, later dismissed

2016-12-31 15:47 UTC, blhough commented on Sensor.cpp
> +#include <Sensor.h>
`#include "Sensor.h"`

2017-01-31 02:30 UTC, blhough requested changes

2017-01-31 02:30 UTC, blhough commented on Sensor.cpp
> +		if (mode == IN)
Though the compiler will surely optimize this, `mode` can never equal `OUT` and `IN` so an `else if` or just an `else` (since mode only has the two values) would be better here.

2017-01-31 02:30 UTC, blhough commented on Sensor.h
> +			int pin;
should be constant to prevent any accidental changing

2017-01-31 02:30 UTC, blhough commented on SensorArray.h
> +		Sensor* sensorArray[8];
use `NUMBER_OF_SENSORS`

2017-01-31 02:30 UTC, blhough commented on SensorArray.cpp
> +			sensorArray[i] = new Sensor(pins[i]);
regarding `pins[]`, this is really dangerous because there is nothing guaranteeing that `pins` is at least size `NUMBER_OF_SENSORS`. If someone calling this function only supplies a `pins` of size 7 then this would read out of bounds and you wouldn't know it (until you called Sensor::setMode(OUT) and potentially set a random pin high and fry something).

Ideally you would make a new class that enforces that the right number of pins is provided (or use std::vector).

2017-01-31 02:30 UTC, blhough commented on Sensor.cpp
> +			digitalWrite(pin, HIGH);
If `Sensor` is only going to be used with the Reflectance Sensor Array then this is fine. However if `Sensor` is to be reused by other sensors types in the project, defaulting the output to HIGH is risky.

2017-01-31 02:30 UTC, blhough commented on SensorArray.cpp
> +		Sensor* sensorArray[NUMBER_OF_SENSORS];
This is a re-declaration of the member variable at SensorArray.h:23. C++ allows this by hiding (shadowing) the variable with the wider scope ([read more about it here](https://en.wikipedia.org/wiki/Variable_shadowing)). So what this means is that when you assign to `sensorArray` on line 5 you are assigning to the local one, not the class level one. So basically a major memory leak when `sensorArray` goes out of scope at the end of the constructor. Every other use of `sensorArray` in the class is using the un-initialized one (bad).


On another note, I know you just learned about pointers, so is good time to learn when pointers are not needed. Notice in your implementation you never move a pointer around, reassign it, pass it to a function etc. You aren't using many of the benefits of pointers but are still stuck with all the negatives (null dereference, memory leak, etc.). The one benefit you are using is that you can delay creating the objects in the array until you are able to put meaningful objects in it, but this is (generally)[https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c43-ensure-that-a-class-has-a-default-constructor] not considered a good enough reason to use pointers.

2017-01-31 02:30 UTC, blhough commented on SensorArray.cpp
> +			delete sensorArray[i];
If `sensorArray` were to be properly initialized (see above) then this is the correct way to handle the de-allocations 🥇

2017-01-31 02:30 UTC, blhough commented on SensorArray.cpp
> +			27;
This probably works by some weird C backwards compatibility idk, but it's not good form.  Just make it a const int LINE_OFFSET if that is all you need

2017-01-31 02:51 UTC, blhough requested changes

2017-01-31 02:51 UTC, blhough commented on SensorArray.cpp
> +	}
Don't forget to allow for 10us after setting high. It is possible that the code already takes that long to go from prepSensor to readSensorValues

2017-01-31 02:51 UTC, blhough commented on SensorArray.cpp
> +					if (sensorArray[sensorNum]->isLow) // if low, record time.
`isLow` is a function, need ()

2017-01-31 02:51 UTC, blhough commented on SensorArray.cpp
> +						lengthOfTime = endTime - startTime;
Are these really necessary ?
could make it
`tempSensorValues[sensorNum] = micros() - startTime;`

2017-01-31 02:51 UTC, blhough commented on SensorArray.cpp
> +	{
If this ends up being too slow/inacurrate I thought of a really fast way using bit operations

2017-04-01 20:48 UTC, merged